CREATE DATABASE IF NOT EXISTS saloondb;
CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS categorydb;
CREATE DATABASE IF NOT EXISTS servicesdb;
CREATE DATABASE IF NOT EXISTS bookingdb;
