CREATE DATABASE IF NOT EXISTS saloondb;
CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS categorydb;
CREATE DATABASE IF NOT EXISTS service-offeringdb;
CREATE DATABASE IF NOT EXISTS bookingdb;
CREATE DATABASE IF NOT EXISTS paymentdb;
